#!/bin/bash

pkill -KILL -F /var/run/suricata.pid 2> /dev/null
rm -f /var/run/suricata.pid

suricata -v -i eth0 -c /etc/suricata/suricata.yaml --pidfile /var/run/suricata.pid &

while true
do
    inotifywait -q -e modify /etc/suricata/securetia.rules
    echo "***********************************************************"
    echo "Reloading rules...                                        *"
    echo "***********************************************************"
    pkill -USR2 -F /var/run/suricata.pid
done

pkill -KILL -F /var/run/suricata.pid

