#!/bin/sh

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends suricata ncat nmap onesixtyone wireshark inotify-tools

rm -f /etc/suricata/suricata.yaml

ln -s $(readlink -f ./suricata.yaml) /etc/suricata/
ln -s $(readlink -f ./securetia.rules) /etc/suricata/rules/
